# Generated by Django 2.1.4 on 2019-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('language', models.CharField(max_length=32)),
                ('Content', models.TextField()),
                ('Level', models.IntegerField()),
            ],
        ),
    ]
