# Generated by Django 2.1.4 on 2019-05-10 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0002_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathToFile', models.FilePathField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Exercise')),
            ],
        ),
    ]
