# Generated by Django 2.1.4 on 2019-05-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0003_unittest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('exercises', models.ManyToManyField(to='ServiceCore.Exercise')),
            ],
        ),
    ]
