# Generated by Django 2.1.4 on 2019-05-10 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0005_tasktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Exercise')),
                ('taskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.TaskType')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Test')),
            ],
        ),
    ]
