# Generated by Django 2.1.4 on 2019-06-01 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0012_auto_20190601_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Level',
            new_name='level',
        ),
    ]
