# Generated by Django 2.1.4 on 2019-06-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0015_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Exercise'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.TaskType'),
        ),
        migrations.AlterField(
            model_name='task',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Test'),
        ),
    ]
