# Generated by Django 2.1.4 on 2019-11-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0022_auto_20191117_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='exercises',
            field=models.ManyToManyField(related_name='exercises', to='ServiceCore.Exercise'),
        ),
    ]
