# Generated by Django 2.1.4 on 2019-12-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0024_test_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='name',
            new_name='title',
        ),
    ]
