# Generated by Django 2.1.4 on 2019-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0025_auto_20191203_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unittest',
            name='pathToFile',
            field=models.FilePathField(max_length=1024),
        ),
    ]
