# Generated by Django 2.1.4 on 2019-12-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0027_auto_20191204_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='pathToFile',
            field=models.FilePathField(max_length=1024),
        ),
    ]
