# Generated by Django 2.1.4 on 2019-12-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0028_auto_20191204_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='unittest',
            name='content',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
