# Generated by Django 2.1.4 on 2019-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0030_auto_20191215_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='allowed_extension',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
