# Generated by Django 2.1.4 on 2020-01-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0032_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='github_link',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='unittest',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_tests', to='ServiceCore.Exercise'),
        ),
    ]
