# Generated by Django 2.1.4 on 2020-01-14 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0033_auto_20200106_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathToFile', models.FilePathField(max_length=1024)),
                ('rate', models.IntegerField()),
                ('github_link', models.CharField(blank=True, max_length=4096, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('exercises_solutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.SolutionExercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='solution',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='pathToFile',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='rate',
        ),
        migrations.AddField(
            model_name='solutiontest',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Solution'),
        ),
        migrations.AddField(
            model_name='solutionexercise',
            name='solution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Solution'),
        ),
    ]
