# Generated by Django 2.1.4 on 2020-01-14 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0035_auto_20200114_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutiontest',
            name='exercises_solutions',
        ),
        migrations.AddField(
            model_name='solutionexercise',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises_solutions', to='ServiceCore.SolutionTest'),
        ),
    ]
