# Generated by Django 2.1.4 on 2020-01-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0036_auto_20200114_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionexercise',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Solution'),
        ),
    ]
