# Generated by Django 2.1.4 on 2020-01-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0038_auto_20200114_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
