# Generated by Django 2.1.4 on 2020-01-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0040_solutionexercise_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutionexercise',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solutiontest',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
