# Generated by Django 2.1.4 on 2020-01-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0041_auto_20200119_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isRated',
            field=models.BooleanField(default=False),
        ),
    ]
