# Generated by Django 2.1.4 on 2020-04-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0043_registrationhash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('hash_value', models.CharField(max_length=40)),
                ('consumed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='registrationhash',
            name='creator',
        ),
        migrations.DeleteModel(
            name='RegistrationHash',
        ),
    ]
