# Generated by Django 2.1.4 on 2020-04-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0045_auto_20200407_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpasswordhash',
            old_name='account_created',
            new_name='consumed',
        ),
    ]
