# Generated by Django 2.1.4 on 2020-05-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCore', '0046_auto_20200407_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCore.Group'),
        ),
    ]
